name: Release from Commit

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      - name: Use latest npm
        run: npm i -g npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Configure git author
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          echo "Configured git author:" && git config user.name && git config user.email

      - name: Detect semver bump type
        id: semver
        run: |
          COMMIT_RAW=$(git log -1 --pretty=%B)
          SUBJECT=$(echo "$COMMIT_RAW" | head -n1)
          echo "Last commit subject: $SUBJECT"
          if [[ "$COMMIT_RAW" == *$'\n'* ]]; then
            echo "(Commit body present, scanning for BREAKING CHANGE)"
          fi

          # Major bump if feat! or fix! (optionally feat(<any chars>)! allowing spaces) OR if body contains BREAKING CHANGE:
          if echo "$SUBJECT" | grep -Eq '^(feat|fix)(\(.*\))?!'; then
            BUMP="major"
          elif [[ "$SUBJECT" == feat!* || "$SUBJECT" == fix!* ]]; then
            BUMP="major"
          elif grep -q "^BREAKING CHANGE:" <<< "$COMMIT_RAW"; then
            BUMP="major"
          elif [[ "$SUBJECT" == feat* ]]; then
            BUMP="minor"
          elif [[ "$SUBJECT" == fix* ]]; then
            BUMP="patch"
          else
            echo "No semantic release trigger found (feat, fix, feat!, fix!, BREAKING CHANGE). Skipping release."
            # Intentionally NOT setting bump output.
            exit 0
          fi

          echo "Bump type: $BUMP"
          echo "bump=$BUMP" >> $GITHUB_OUTPUT

      - name: Bump version
        if: steps.semver.outputs.bump
        run: |
          npm version ${{ steps.semver.outputs.bump }} -m "chore(release): %s [skip ci]"
          git push
          git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to npm
        if: steps.semver.outputs.bump
        run: npm publish
